### PR TITLE
Use ppx, result

### PR DESCRIPTION
**Pull request by djs55**
- use upstream result module
- update to ppx

Obsoletes #46

### CODE REVIEW

**Comment by jonludlam** [comment]
Ah, snap! just done this myself! Ah well :-)

**Comment by jonludlam** [comment]
Hmm, something wrong with the coverage stuff.

**Comment by jonludlam** [comment]
Looks like it was still using old bisect - have made a new PR to switch to bisect_ppx.

**Comment by djs55** [comment]
thanks!

**Pull request merged**
